### ISSUE TITLE
INET_ATON and INET_NTOA

### ISSUE THREAD

**Issue by h4cc** [bordeltabernacle/IPA#18]
I could not find these conversion functions. They take a address and convert it to a integer.
May be handy for storing many ips in a efficient format with ordering or using addresses as a key inside maps.

More infos: http://dev.mysql.com/doc/refman/5.0/en/miscellaneous-functions.html#function_inet-aton

May i implement that feature? :)

**Comment by bordeltabernacle** [comment]
Hi, yeah for sure!

This isn't a format I'm familiar with, hence the only reason I've not implemented it.

Thanks!

**Comment by h4cc** [comment]
I am working on it.

@bordeltabernacle Is there a preferred form for ip addresses? Like is the string `"192.168.1.2"` preferred over the octed `{192, 168, 1, 2}`.
The `address_to_number` function i am working can accept both, but what should `number_to_address` return? I would favor to return a string for `number_to_address` and add another function like `number_to_octet` returning a octet.

**Comment by h4cc** [comment]
@bordeltabernacle Have a look at what i did please.

**Comment by h4cc** [comment]
I read that PostgreSQL does not have UnsignedInteger Column Types. There are also some implementations, that use signed integer implementations for this feature: http://php.net/manual/en/function.ip2long.php

The current implementation is returning unsigned integer. I will try to find out how to convert unsigned ints to signed ints in elixir.

**Comment by bordeltabernacle** [comment]
This is great, thankyou. A couple of things;

So, as it is at the moment I've tried to have it so that each conversion function doesn't mind in what form it takes the ip address/subnet mask and will take `dotted decimal`, `hexadecimal`, `binary`, `dotted binary`, `tuple` and `cidr` and convert it as necessary.

Ideally this would be the case for `to_number` as well, it should be able to take all form's of ip address, and subnet mask, and convert it to a valid number.  And all the other `to_*` functions should then be able to take a number and convert it too.  The biggest problem I can see here is in the [`pre_transformation_validations`](https://github.com/bordeltabernacle/IPA/blob/master/lib/ipa.ex#L383) function where any integer over 32 is just assumed to be invalid as this is as high as a `cidr` mask will go.  I'm thinking I might have to break the functions up, either into separate `Address` & `Subnet` modules or into `address_to_*` and `mask_to_*` functions.  I wasn't overly happy with the `pre_transformation_validations` anyway.  

The `to_*` functions also have built in validation, and privately transform from, and to, a common data structure to enable simpler transformation across the functions. Each function follows a similar path: performs any pre-transformation-validations, converts the argument to a 4 element list, validates that list, then if valid converts the list to the required form.  This path gives us a couple of benefits; apart from the `pre-transformation-validations`, we only have to validate one data structure, the 4 element list, rather than having to validate hex & binary etc.  It also means we only have to write one function to convert a 4 element list to a number, and another to convert a number to a 4 element list, we can then utilise the already existing functions to transform a number to the other forms, and the other form into a number, via the 4 element list. Does that make sense? I realise I'm rambling!

Yeah, unsigned is fine for our needs as we don't need to represent negative numbers, but if it's a case of making return values work for other services such as Postgres than that could be useful.

Thanks @h4cc !

**Comment by h4cc** [comment]
Looks like development has halted here, because some preconditions to my PR might not be met.

@bordeltabernacle A idea how this could proceed?

**Comment by bordeltabernacle** [comment]
Hi @h4cc 
Yeah, I admit I've not paid much attention to this lib for a while, my involvement with Elixir has diminished somewhat recently due to work stuff.  But, anyway, I'm not abandoning this just yet.  I'm starting a develop branch where I'm going to start breaking the API into `Address`, `Mask`, & `Network` modules, as I think this will be the best thing moving forward, hopefully at this point we can get these functions in.
I welcome any feedback you have on this as I'm learning as I go and may not be sure of the most practical way forward from an *Elixir* point of view.
How does this sound to you?

**Comment by h4cc** [comment]
Sounds good. Ping me when your branch is ready :)

**Comment by bordeltabernacle** [comment]
sorry @h4cc I've deprecated this project as I'm not spending any time with Elixir anymore, feel free to fork it
